export const LOGIN_USER = "LOGIN_USER";
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const REQUEST_LOCKS = "REQUEST_LOCKS";
export const REQUEST_LOCKS_SUCCESS = "REQUEST_LOCKS_SUCCESS";
export const REQUEST_LOCKS_ERROR = "REQUEST_LOCKS_ERROR";

export const INIT_SERVER = "INIT_SERVER";
export const INIT_SERVER_SUCCESS = "INIT_SERVER_SUCCESS";
export const INIT_SERVER_ERROR = "INIT_SERVER_ERROR";

export const REQUEST_PASSCODES = "REQUEST_PASSCODES";
export const REQUEST_PASSCODES_SUCCESS = "REQUEST_PASSCODES_SUCCESS";
export const REQUEST_PASSCODES_ERROR = "REQUEST_PASSCODES_ERROR";

export const EDIT_PASSCODE = "EDIT_PASSCODE"
export const EDIT_PASSCODE_SUCCESS = "EDIT_PASSCODE_SUCCESS";
export const EDIT_PASSCODE_ERROR = "EDIT_PASSCODE_ERROR";

export const DELETE_PASSCODE = "DELETE_PASSCODE";
export const DELETE_PASSCODE_SUCCESS = "DELETE_PASSCODE_SUCCESS";
export const DELETE_PASSCODE_ERROR = "DELETE_PASSCODE_ERROR";

export const ADD_PASSCODE = "ADD_PASSCODE";
export const ADD_PASSCODE_SUCCESS = "ADD_PASSCODE_SUCCESS";
export const ADD_PASSCODE_ERROR = "ADD_PASSCODE_ERROR";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const GET_RECORDS = "GET_RECORDS";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_ERROR = "GET_RECORDS_ERROR";

export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_RESERVATIONS_ERROR = "GET_RESERVATIONS_ERROR";
